from .base_message_processor import MessageProcessor


class DeepSeekR1DistillMessageProcessor(MessageProcessor):
    """
    Message processor for DeepSeek-R1-Distill-Qwen/Llama series models.
    Only supports single-turn conversation, no tool calls.

    Prompt format (generated by tokenizer.apply_chat_template):
        <｜begin▁of▁sentence｜>{system}<｜User｜>{user}<｜Assistant｜><think>\n

    Full response format:
        {thinking}\n</think>\n\n{content}<｜end▁of▁sentence｜>

    Special token IDs:
        151643  <｜end▁of▁sentence｜>   (eos / stop token)
        151644  <｜User｜>
        151645  <｜Assistant｜>
        151646  <｜begin▁of▁sentence｜>  (bos)
        151648  <think>
        151649  </think>
    """
    
    BOS = "<｜begin▁of▁sentence｜>"
    EOS = "<｜end▁of▁sentence｜>"
    USER = "<｜User｜>"
    ASSISTANT = "<｜Assistant｜>"
    THINK_START = "<think>"
    THINK_END = "</think>"

    def __init__(self, tokenizer, **kwargs):
        self.tokenizer = tokenizer

    def apply_chat_template(
        self,
        messages: list,
        stop_token: str = None,
        add_special_tokens: bool = True,
    ):
        for message in messages:
            assert "assistant" not in message["role"]
        return self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )

    def parse_model_response(self, response: str, truncated: bool = False, aborted: bool = False):
        """
        Parse the raw response generated by sglang.

        Normal response format: "{thinking}\n</think>\n\n{content}<｜end▁of▁sentence｜>"
        When truncated/aborted, save as-is without format validation.
        """
        raw_response = response
        stop_token = None
        ill_formed_reasons = []
        finish_turn = False

        # truncated / aborted: return as-is
        if truncated:
            return [{"role": "assistant", "truncated_content": raw_response}], stop_token, False, finish_turn
        if aborted:
            return [{"role": "assistant", "aborted_content": raw_response}], stop_token, False, finish_turn

        # strip stop token
        if response.endswith(self.EOS):
            stop_token = self.EOS
            response = response[:-len(stop_token)]
        if not stop_token:
            print(f"NOT FOUND STOP TOKEN: {response}")
            return [{"role": "assistant", "aborted_content": raw_response}], stop_token, False, finish_turn

        # validate thinking format: should have exactly one </think>
        if response.count(self.THINK_END) != 1:
            ill_formed_reasons.append("Wrong thinking format.")

        # extract reasoning_content and content
        reasoning_content = response
        content = ""
        if self.THINK_END in response:
            reasoning_content, content = response.rsplit(self.THINK_END, 1)
            reasoning_content = reasoning_content.removesuffix("\n")
            content = content.removeprefix("\n\n")

        # validate content format
        if not reasoning_content:
            ill_formed_reasons.append("Missing reasoning_content.")
        if not content:
            ill_formed_reasons.append("Missing response content.")
        if content:
            for special_token in [self.BOS, self.EOS, self.USER, self.ASSISTANT, self.THINK_START, self.THINK_END]:  # LNY: content still has special tokens after stripping stop token, abnormal
                if special_token in content:
                    ill_formed_reasons.append(f"Content contains special token: {special_token}")

        message = {"role": "assistant"}
        if reasoning_content:
            message["reasoning_content"] = reasoning_content
        if content:
            message["content"] = content
        if ill_formed_reasons:
            message["ill_formed_content"] = raw_response
            message["ill_formed_reasons"] = ill_formed_reasons
            print(f"ILL FORMED RESPONSE:\n{[str(raw_response)]}\nILL FORMED REASON:\n{ill_formed_reasons}")

        finish_turn = True
        return [message], stop_token, len(ill_formed_reasons) > 0, finish_turn
